### ISSUE TITLE
Is the plugin working?

### ISSUE THREAD

**Issue by Gapito2** [michaelwilhelmsen/sp-woocommerce-outfits#1]
Hi, I've downloaded and installed the plugin, created an outfit, but the page shows a 404 error, it doesn't exist. Very good idea, by the way.

**Comment by michaelwilhelmsen** [comment]
Hi @Gapito2! I'm sorry to say, but the plugin is far from finished yet. I will resume work on it later this year. I will make sure to update the readme so others don't download it believing it will work.

**Comment by Gapito2** [comment]
Ah, ok, don't worry at all. I will looking forward for its released. Thank you for your work! :)

PS: Please, let us know when you finish it.

**Comment by Gapito2** [comment]
Hi! Any news from the plugin, Michael? It would be nice to see how it works!

:)

**Comment by michaelwilhelmsen** [comment]
Hi, still haven't had time to check in on this. I will commit changes as soon as they are made, so you'll know once I'm working on it 🙂
